# Generated by Django 4.0.4 on 2022-05-25 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AccountHolderName', models.CharField(max_length=100)),
                ('BankName', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('RelationField', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('CIFNumber', models.CharField(max_length=20)),
                ('MICRNumber', models.CharField(max_length=20)),
                ('AccountType', models.CharField(max_length=100)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Address', models.TextField()),
                ('AccountNumber', models.CharField(max_length=18)),
                ('IFSC_code', models.CharField(max_length=18)),
                ('Pin', models.CharField(max_length=6)),
                ('Picture', models.ImageField(upload_to='pictures/')),
                ('Token', models.CharField(blank=True, max_length=100, null=True)),
                ('Token_created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('TotalBalance', models.FloatField(blank=True, default=0, null=True)),
                ('CreateAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
